plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\haleemmamdouh\\Desktop\\Bond_Touch_Prototype\\pwa_app"
publishOrigin = "default"
base = "C:\\Users\\haleemmamdouh\\Desktop\\Bond_Touch_Prototype\\pwa_app"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]